import { Receipt, Participant } from '../types';

export const DEFAULT_PARTICIPANTS: Participant[] = [
  { id: 'p1', name: 'Alex M.', color: '#3B82F6', avatarInitials: 'AM' },
  { id: 'p2', name: 'Jordan K.', color: '#10B981', avatarInitials: 'JK' },
  { id: 'p3', name: 'Taylor S.', color: '#F59E0B', avatarInitials: 'TS' },
  { id: 'p4', name: 'Morgan L.', color: '#8B5CF6', avatarInitials: 'ML' },
];

export const SAMPLE_RECEIPTS: { title: string; subtitle: string; receipt: Receipt }[] = [
  {
    title: 'Dinner at Trattoria Rustica',
    subtitle: '4 people · Shared appetizers, mains & wine · 18% Tip',
    receipt: {
      id: 'sample-dinner-1',
      merchant: 'Trattoria Rustica',
      date: '2026-09-26',
      currency: '$',
      tags: ['Birthday Dinner', 'Work Trip'],
      items: [
        {
          id: 'item-1',
          name: 'Crispy Calamari & Truffle Aioli',
          quantity: 1,
          unitPrice: 18.5,
          totalPrice: 18.5,
          category: 'Appetizers',
          assignedTo: [
            { participantId: 'p1', shares: 1 },
            { participantId: 'p2', shares: 1 },
            { participantId: 'p3', shares: 1 },
            { participantId: 'p4', shares: 1 },
          ],
        },
        {
          id: 'item-2',
          name: 'Handmade Pappardelle Wild Boar',
          quantity: 1,
          unitPrice: 28.0,
          totalPrice: 28.0,
          category: 'Entrees',
          assignedTo: [{ participantId: 'p1', shares: 1 }],
        },
        {
          id: 'item-3',
          name: 'Pan-Seared Chilean Sea Bass',
          quantity: 1,
          unitPrice: 36.0,
          totalPrice: 36.0,
          category: 'Entrees',
          assignedTo: [{ participantId: 'p2', shares: 1 }],
        },
        {
          id: 'item-4',
          name: 'Wood-Fired Margherita Pizza',
          quantity: 1,
          unitPrice: 22.0,
          totalPrice: 22.0,
          category: 'Entrees',
          assignedTo: [
            { participantId: 'p3', shares: 1 },
            { participantId: 'p4', shares: 1 },
          ],
        },
        {
          id: 'item-5',
          name: 'Ribeye Steak 14oz (Dry Aged)',
          quantity: 1,
          unitPrice: 48.0,
          totalPrice: 48.0,
          category: 'Entrees',
          assignedTo: [{ participantId: 'p4', shares: 1 }],
        },
        {
          id: 'item-6',
          name: 'Chianti Classico Riserva (Bottle)',
          quantity: 1,
          unitPrice: 56.0,
          totalPrice: 56.0,
          category: 'Drinks',
          assignedTo: [
            { participantId: 'p1', shares: 1 },
            { participantId: 'p2', shares: 1 },
            { participantId: 'p4', shares: 1 },
          ], // Taylor doesn't drink
        },
        {
          id: 'item-7',
          name: 'Classic Espresso Tiramisu',
          quantity: 2,
          unitPrice: 12.0,
          totalPrice: 24.0,
          category: 'Desserts',
          assignedTo: [
            { participantId: 'p1', shares: 1 },
            { participantId: 'p2', shares: 1 },
            { participantId: 'p3', shares: 1 },
            { participantId: 'p4', shares: 1 },
          ],
        },
      ],
      discount: 0,
      discountPercentage: 0,
      taxMode: 'percentage',
      taxRate: 8.875,
      taxAmount: 0,
      tipMode: 'percentage',
      tipRate: 18,
      tipAmount: 0,
      tipBasis: 'pre_tax',
      fees: [
        {
          id: 'fee-1',
          name: 'Credit Card Processing Fee (3%)',
          amount: 0,
          isPercentage: true,
          percentageValue: 3,
        },
      ],
      notes: 'Group dinner Friday night at downtown location.',
      allocationStrategy: 'proportional',
    },
  },
  {
    title: 'Weekend Cabin Grocery & Supplies',
    subtitle: 'Group grocery run · Equal & custom snack splits',
    receipt: {
      id: 'sample-groceries-2',
      merchant: 'Whole Harvest Market',
      date: '2026-09-25',
      currency: '$',
      tags: ['Groceries'],
      items: [
        {
          id: 'g-1',
          name: 'Organic Sourdough Bread & Butter',
          quantity: 2,
          unitPrice: 6.5,
          totalPrice: 13.0,
          category: 'Bakery',
          assignedTo: [
            { participantId: 'p1', shares: 1 },
            { participantId: 'p2', shares: 1 },
            { participantId: 'p3', shares: 1 },
            { participantId: 'p4', shares: 1 },
          ],
        },
        {
          id: 'g-2',
          name: 'Cage-Free Eggs (24ct) & Bacon',
          quantity: 1,
          unitPrice: 16.5,
          totalPrice: 16.5,
          category: 'Breakfast',
          assignedTo: [
            { participantId: 'p1', shares: 1 },
            { participantId: 'p2', shares: 1 },
            { participantId: 'p3', shares: 1 },
            { participantId: 'p4', shares: 1 },
          ],
        },
        {
          id: 'g-3',
          name: 'Artisan Cheeses & Crackers Platter',
          quantity: 1,
          unitPrice: 28.0,
          totalPrice: 28.0,
          category: 'Snacks',
          assignedTo: [
            { participantId: 'p1', shares: 1 },
            { participantId: 'p3', shares: 1 },
          ],
        },
        {
          id: 'g-4',
          name: 'Cold Brew Coffee Concentrate (2pk)',
          quantity: 2,
          unitPrice: 11.0,
          totalPrice: 22.0,
          category: 'Beverage',
          assignedTo: [
            { participantId: 'p2', shares: 1 },
            { participantId: 'p4', shares: 1 },
          ],
        },
        {
          id: 'g-5',
          name: 'BBQ Grilling Steaks & Veggie Skewers',
          quantity: 1,
          unitPrice: 54.0,
          totalPrice: 54.0,
          category: 'Meat/Produce',
          assignedTo: [
            { participantId: 'p1', shares: 1 },
            { participantId: 'p2', shares: 1 },
            { participantId: 'p3', shares: 1 },
            { participantId: 'p4', shares: 1 },
          ],
        },
      ],
      discount: 10,
      discountPercentage: 0,
      taxMode: 'percentage',
      taxRate: 6.25,
      taxAmount: 0,
      tipMode: 'percentage',
      tipRate: 0,
      tipAmount: 0,
      tipBasis: 'pre_tax',
      fees: [
        {
          id: 'bag-fee',
          name: 'Eco Paper Bags',
          amount: 0.5,
          isPercentage: false,
        },
      ],
      notes: 'Cabin supplies split.',
      allocationStrategy: 'proportional',
    },
  },
];
